// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Js_boolean = require("bs-platform/lib/js/js_boolean.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");

var component = ReasonReact.statelessComponent("Item");

function make(item, onDelete, onToggleComplete, _) {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      var match = item[/* completed */1];
      var textStyle = match !== 0 ? ({
            textDecoration: "line-through"
          }) : { };
      return React.createElement("div", undefined, React.createElement("input", {
                      checked: Js_boolean.to_js_boolean(item[/* completed */1]),
                      type: "checkbox",
                      onChange: onToggleComplete
                    }), React.createElement("span", {
                      style: textStyle
                    }, item[/* description */2]), React.createElement("button", {
                      style: {
                        margin: "0.5rem"
                      },
                      onClick: onDelete
                    }, "Delete"));
    });
  return newrecord;
}

exports.component = component;
exports.make = make;
/* component Not a pure module */
