// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");

function getCurrentTime() {
  return new Date(Date.now()).toLocaleTimeString();
}

var component = ReasonReact.reducerComponent("Counter");

function make() {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function (self) {
      var time = self[/* state */2][/* time */0];
      return React.createElement("div", undefined, React.createElement("button", {
                      onClick: (function () {
                          return Curry._1(self[/* send */4], /* Tick */0);
                        })
                    }, time));
    });
  newrecord[/* initialState */10] = (function () {
      return /* record */[/* time */"Click me"];
    });
  newrecord[/* reducer */12] = (function (_, _$1) {
      return /* UpdateWithSideEffects */Block.__(3, [
                /* record */[/* time */new Date(Date.now()).toLocaleTimeString()],
                (function (self) {
                    setTimeout((function () {
                            return Curry._1(self[/* send */4], /* Tick */0);
                          }), 1000);
                    return /* () */0;
                  })
              ]);
    });
  return newrecord;
}

exports.getCurrentTime = getCurrentTime;
exports.component = component;
exports.make = make;
/* component Not a pure module */
