// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Slugify = require("@sindresorhus/slugify");

console.log(Slugify("Batman and Robin"));

console.log(Slugify("Batman and Robin", {
          separator: "?"
        }));

var component = ReasonReact.statelessComponent("Interop");

function make() {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return React.createElement("div", undefined, "Open your console");
    });
  return newrecord;
}

exports.component = component;
exports.make = make;
/*  Not a pure module */
