// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");

function addSecond(param) {
  var seconds = param[/* seconds */1];
  var minutes = param[/* minutes */0];
  if (seconds < 60) {
    return /* record */[
            /* minutes */minutes,
            /* seconds */seconds + 1 | 0
          ];
  } else {
    return /* record */[
            /* minutes */minutes + 1 | 0,
            /* seconds */0
          ];
  }
}

function timeToString(param) {
  return String(param[/* minutes */0]) + (" minutes, " + (String(param[/* seconds */1]) + " seconds!"));
}

var component = ReasonReact.reducerComponent("Counter");

var initialTime = /* record */[
  /* minutes */0,
  /* seconds */0
];

function make() {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function (self) {
      var timerState = self[/* state */2][/* timerState */1];
      var time = self[/* state */2][/* time */0];
      var actionWhileTicking = function () {
        return Curry._1(self[/* send */4], /* Tick */0);
      };
      var match = timerState !== 0 ? /* tuple */[
          "Start",
          /* StartTicking */[actionWhileTicking]
        ] : /* tuple */[
          "Stop",
          /* Stop */1
        ];
      var action = match[1];
      return React.createElement("div", undefined, React.createElement("p", undefined, timeToString(time)), React.createElement("button", {
                      onClick: (function () {
                          return Curry._1(self[/* send */4], action);
                        })
                    }, match[0]));
    });
  newrecord[/* initialState */10] = (function () {
      return /* record */[
              /* time */initialTime,
              /* timerState : Stopped */1,
              /* intervalId */[/* None */0]
            ];
    });
  newrecord[/* reducer */12] = (function (action, state) {
      if (typeof action === "number") {
        if (action !== 0) {
          var match = state[/* intervalId */2][0];
          if (match) {
            clearInterval(match[0]);
            state[/* intervalId */2][0] = /* None */0;
          }
          return /* Update */Block.__(0, [/* record */[
                      /* time */initialTime,
                      /* timerState : Stopped */1,
                      /* intervalId */state[/* intervalId */2]
                    ]]);
        } else {
          return /* Update */Block.__(0, [/* record */[
                      /* time */addSecond(state[/* time */0]),
                      /* timerState */state[/* timerState */1],
                      /* intervalId */state[/* intervalId */2]
                    ]]);
        }
      } else {
        state[/* intervalId */2][0] = /* Some */[setInterval(action[0], 1000)];
        return /* Update */Block.__(0, [/* record */[
                    /* time */state[/* time */0],
                    /* timerState : Ticking */0,
                    /* intervalId */state[/* intervalId */2]
                  ]]);
      }
    });
  return newrecord;
}

exports.addSecond = addSecond;
exports.timeToString = timeToString;
exports.component = component;
exports.initialTime = initialTime;
exports.make = make;
/* component Not a pure module */
